### ISSUE TITLE
Using the action fails on missing name

### ISSUE THREAD

**Issue by mcpierce** [riskledger/generate-changelog#17]
I just tried out your action on my project and am getting the following when generating a changelog:

```
2020-08-22T12:16:07.6128751Z /home/runner/work/_actions/RiskLedger/generate-changelog/v1.2/node_modules/@actions/core/lib/core.js:78
2020-08-22T12:16:07.6129285Z         throw new Error(`Input required and not supplied: ${name}`);
2020-08-22T12:16:07.6129533Z         ^
2020-08-22T12:16:07.6129713Z 
2020-08-22T12:16:07.6129973Z Error: Input required and not supplied: to
2020-08-22T12:16:07.6130986Z     at Object.getInput (/home/runner/work/_actions/RiskLedger/generate-changelog/v1.2/node_modules/@actions/core/lib/core.js:78:15)
2020-08-22T12:16:07.6132227Z     at Object.<anonymous> (/home/runner/work/_actions/RiskLedger/generate-changelog/v1.2/main.js:11:20)
2020-08-22T12:16:07.6132575Z     at Module._compile (internal/modules/cjs/loader.js:959:30)
2020-08-22T12:16:07.6132815Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
2020-08-22T12:16:07.6133036Z     at Module.load (internal/modules/cjs/loader.js:815:32)
2020-08-22T12:16:07.6133257Z     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
2020-08-22T12:16:07.6133478Z     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
2020-08-22T12:16:07.6133692Z     at internal/main/run_main_module.js:17:11
2020-08-22T12:16:07.6205508Z Post job cleanup.
2020-08-22T12:16:07.7217544Z [command]/usr/bin/git version
2020-08-22T12:16:07.7275395Z git version 2.28.0
```

**Comment by safinn** [comment]
As of version 2 the inputs `to` and `from` are not required which should solve your problem.
